name: Presentation
on: [push]
jobs:
  github:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: refs/heads/master
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - name: Make HTML
      run: npx @marp-team/marp-cli ${GITHUB_REPOSITORY#*/}.md
    - name: Make PDF
      run: npx @marp-team/marp-cli ${GITHUB_REPOSITORY#*/}.md --pdf
